name: markdown_quill
description: Convert between quill (delta) format and markdown
version: 4.3.0
repository: https://github.com/TarekkMA/markdown_quill
publish_to: none

environment:
  sdk: ">=3.1.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  charcode: ^1.3.1
  collection: ^1.18.0
  flutter_quill:
    git:
      url: https://github.com/input-output-hk/flutter-quill
      ref: 81aa649db3268b0b69440db1b3313af90d393ae7
  markdown: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.10.0
  very_good_analysis: ^5.1.0
